USE daily;

CREATE TABLE message_(
	id BIGINT AUTO_INCREMENT,
	name VARCHAR(20),
	message VARCHAR(500),
	time DATETIME DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8 COMMENT '¡Ù—‘±Ì';